openapi: 3.0.0
info:
  title: Gmail API
  description: The Gmail API lets you view and manage Gmail mailbox data like
    threads, messages, and labels.
  version: v1
  contact:
    url: https://developers.google.com/gmail/api/
servers:
  - url: https://gmail.googleapis.com/
    description: Production server
paths:
  /gmail/v1/users/{userId}/profile:
    get:
      operationId: users.gmail.users.getProfile
      description: Gets the current user's Gmail profile.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/watch:
    post:
      operationId: users.gmail.users.watch
      description: Set up or update a push notification watch on the given user mailbox.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/stop:
    post:
      operationId: users.gmail.users.stop
      description: Stop receiving push notifications for the given user mailbox.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/drafts/{id}:
    delete:
      operationId: users.drafts.gmail.users.drafts.delete
      description: Immediately and permanently deletes the specified draft. Does not
        simply trash it.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.action.compose
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
    get:
      operationId: users.drafts.gmail.users.drafts.get
      description: Gets the specified draft.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
    put:
      operationId: users.drafts.gmail.users.drafts.update
      description: Replaces a draft's content.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.action.compose
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/drafts:
    post:
      operationId: users.drafts.gmail.users.drafts.create
      description: Creates a new draft with the `DRAFT` label.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.action.compose
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
    get:
      operationId: users.drafts.gmail.users.drafts.list
      description: Lists the drafts in the user's mailbox.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/drafts/send:
    post:
      operationId: users.drafts.gmail.users.drafts.send
      description: Sends the specified, existing draft to the recipients in the `To`,
        `Cc`, and `Bcc` headers.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.action.compose
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/history:
    get:
      operationId: users.history.gmail.users.history.list
      description: Lists the history of all changes to the given mailbox. History
        results are returned in chronological order (increasing `historyId`).
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/messages/{id}/trash:
    post:
      operationId: users.messages.gmail.users.messages.trash
      description: Moves the specified message to the trash.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/messages/{id}/untrash:
    post:
      operationId: users.messages.gmail.users.messages.untrash
      description: Removes the specified message from the trash.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/messages/{id}:
    delete:
      operationId: users.messages.gmail.users.messages.delete
      description: Immediately and permanently deletes the specified message. This
        operation cannot be undone. Prefer `messages.trash` instead.
      security:
        - OAuth2:
            - https://mail.google.com/
    get:
      operationId: users.messages.gmail.users.messages.get
      description: Gets the specified message.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.message.action
            - https://www.googleapis.com/auth/gmail.addons.current.message.metadata
            - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/messages/batchDelete:
    post:
      operationId: users.messages.gmail.users.messages.batchDelete
      description: Deletes many messages by message ID. Provides no guarantees that
        messages were not already deleted or even existed at all.
      security:
        - OAuth2:
            - https://mail.google.com/
  /gmail/v1/users/{userId}/messages/import:
    post:
      operationId: users.messages.gmail.users.messages.import
      description: Imports a message into only this user's mailbox, with standard
        email delivery scanning and classification similar to receiving via
        SMTP. This method doesn't perform SPF checks, so it might not work for
        some spam messages, such as those attempting to perform domain spoofing.
        This method does not send a message.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.insert
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/messages:
    post:
      operationId: users.messages.gmail.users.messages.insert
      description: Directly inserts a message into only this user's mailbox similar to
        `IMAP APPEND`, bypassing most scanning and classification. Does not send
        a message.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.insert
            - https://www.googleapis.com/auth/gmail.modify
    get:
      operationId: users.messages.gmail.users.messages.list
      description: Lists the messages in the user's mailbox.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/messages/send:
    post:
      operationId: users.messages.gmail.users.messages.send
      description: Sends the specified message to the recipients in the `To`, `Cc`,
        and `Bcc` headers. For example usage, see [Sending
        email](https://developers.google.com/gmail/api/guides/sending).
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.action.compose
            - https://www.googleapis.com/auth/gmail.compose
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.send
  /gmail/v1/users/{userId}/messages/{id}/modify:
    post:
      operationId: users.messages.gmail.users.messages.modify
      description: Modifies the labels on the specified message.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/messages/batchModify:
    post:
      operationId: users.messages.gmail.users.messages.batchModify
      description: Modifies the labels on the specified messages.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}:
    get:
      operationId: users.messages.attachments.gmail.users.messages.attachments.get
      description: Gets the specified message attachment.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.message.action
            - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/labels:
    post:
      operationId: users.labels.gmail.users.labels.create
      description: Creates a new label.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.labels
            - https://www.googleapis.com/auth/gmail.modify
    get:
      operationId: users.labels.gmail.users.labels.list
      description: Lists all labels in the user's mailbox.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.labels
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/labels/{id}:
    delete:
      operationId: users.labels.gmail.users.labels.delete
      description: Immediately and permanently deletes the specified label and removes
        it from any messages and threads that it is applied to.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.labels
            - https://www.googleapis.com/auth/gmail.modify
    get:
      operationId: users.labels.gmail.users.labels.get
      description: Gets the specified label.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.labels
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
    put:
      operationId: users.labels.gmail.users.labels.update
      description: Updates the specified label.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.labels
            - https://www.googleapis.com/auth/gmail.modify
    patch:
      operationId: users.labels.gmail.users.labels.patch
      description: Patch the specified label.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.labels
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/threads/{id}/trash:
    post:
      operationId: users.threads.gmail.users.threads.trash
      description: Moves the specified thread to the trash. Any messages that belong
        to the thread are also moved to the trash.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/threads/{id}/untrash:
    post:
      operationId: users.threads.gmail.users.threads.untrash
      description: Removes the specified thread from the trash. Any messages that
        belong to the thread are also removed from the trash.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/threads/{id}:
    delete:
      operationId: users.threads.gmail.users.threads.delete
      description: Immediately and permanently deletes the specified thread. Any
        messages that belong to the thread are also deleted. This operation
        cannot be undone. Prefer `threads.trash` instead.
      security:
        - OAuth2:
            - https://mail.google.com/
    get:
      operationId: users.threads.gmail.users.threads.get
      description: Gets the specified thread.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.addons.current.message.action
            - https://www.googleapis.com/auth/gmail.addons.current.message.metadata
            - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/threads:
    get:
      operationId: users.threads.gmail.users.threads.list
      description: Lists the threads in the user's mailbox.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.metadata
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
  /gmail/v1/users/{userId}/threads/{id}/modify:
    post:
      operationId: users.threads.gmail.users.threads.modify
      description: Modifies the labels applied to the thread. This applies to all
        messages in the thread.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
  /gmail/v1/users/{userId}/settings/imap:
    get:
      operationId: users.settings.gmail.users.settings.getImap
      description: Gets IMAP settings.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    put:
      operationId: users.settings.gmail.users.settings.updateImap
      description: Updates IMAP settings.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
  /gmail/v1/users/{userId}/settings/pop:
    get:
      operationId: users.settings.gmail.users.settings.getPop
      description: Gets POP settings.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    put:
      operationId: users.settings.gmail.users.settings.updatePop
      description: Updates POP settings.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
  /gmail/v1/users/{userId}/settings/vacation:
    get:
      operationId: users.settings.gmail.users.settings.getVacation
      description: Gets vacation responder settings.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    put:
      operationId: users.settings.gmail.users.settings.updateVacation
      description: Updates vacation responder settings.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
  /gmail/v1/users/{userId}/settings/language:
    get:
      operationId: users.settings.gmail.users.settings.getLanguage
      description: Gets language settings.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    put:
      operationId: users.settings.gmail.users.settings.updateLanguage
      description: Updates language settings. If successful, the return object
        contains the `displayLanguage` that was saved for the user, which may
        differ from the value passed into the request. This is because the
        requested `displayLanguage` may not be directly supported by Gmail but
        have a close variant that is, and so the variant may be chosen and saved
        instead.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
  /gmail/v1/users/{userId}/settings/autoForwarding:
    get:
      operationId: users.settings.gmail.users.settings.getAutoForwarding
      description: Gets the auto-forwarding setting for the specified account.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    put:
      operationId: users.settings.gmail.users.settings.updateAutoForwarding
      description: Updates the auto-forwarding setting for the specified account. A
        verified forwarding address must be specified when auto-forwarding is
        enabled. This method is only available to service account clients that
        have been delegated domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/sendAs:
    get:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.list
      description: Lists the send-as aliases for the specified account. The result
        includes the primary send-as address associated with the account as well
        as any custom "from" aliases.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    post:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.create
      description: Creates a custom "from" send-as alias. If an SMTP MSA is specified,
        Gmail will attempt to connect to the SMTP service to validate the
        configuration before creating the alias. If ownership verification is
        required for the alias, a message will be sent to the email address and
        the resource's verification status will be set to `pending`; otherwise,
        the resource will be created with verification status set to `accepted`.
        If a signature is provided, Gmail will sanitize the HTML before saving
        it with the alias. This method is only available to service account
        clients that have been delegated domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}:
    get:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.get
      description: Gets the specified send-as alias. Fails with an HTTP 404 error if
        the specified address is not a member of the collection.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    put:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.update
      description: Updates a send-as alias. If a signature is provided, Gmail will
        sanitize the HTML before saving it with the alias. Addresses other than
        the primary address for the account can only be updated by service
        account clients that have been delegated domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    patch:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.patch
      description: Patch the specified send-as alias.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    delete:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.delete
      description: Deletes the specified send-as alias. Revokes any verification that
        may have been required for using it. This method is only available to
        service account clients that have been delegated domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify:
    post:
      operationId: users.settings.sendAs.gmail.users.settings.sendAs.verify
      description: Sends a verification email to the specified send-as alias address.
        The verification status must be `pending`. This method is only available
        to service account clients that have been delegated domain-wide
        authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo:
    get:
      operationId: users.settings.sendAs.smimeInfo.gmail.users.settings.sendAs.smimeInfo.list
      description: Lists S/MIME configs for the specified send-as alias.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    post:
      operationId: users.settings.sendAs.smimeInfo.gmail.users.settings.sendAs.smimeInfo.insert
      description: Insert (upload) the given S/MIME config for the specified send-as
        alias. Note that pkcs12 format is required for the key.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}:
    get:
      operationId: users.settings.sendAs.smimeInfo.gmail.users.settings.sendAs.smimeInfo.get
      description: Gets the specified S/MIME config for the specified send-as alias.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    delete:
      operationId: users.settings.sendAs.smimeInfo.gmail.users.settings.sendAs.smimeInfo.delete
      description: Deletes the specified S/MIME config for the specified send-as alias.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault:
    post:
      operationId: users.settings.sendAs.smimeInfo.gmail.users.settings.sendAs.smimeInfo.setDefault
      description: Sets the default S/MIME config for the specified send-as alias.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/identities:
    post:
      operationId: users.settings.cse.identities.gmail.users.settings.cse.identities.create
      description: Creates and configures a client-side encryption identity that's
        authorized to send mail from the user account. Google publishes the
        S/MIME certificate to a shared domain-wide directory so that people
        within a Google Workspace organization can encrypt and send mail to the
        identity.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    get:
      operationId: users.settings.cse.identities.gmail.users.settings.cse.identities.list
      description: Lists the client-side encrypted identities for an authenticated user.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}:
    delete:
      operationId: users.settings.cse.identities.gmail.users.settings.cse.identities.delete
      description: Deletes a client-side encryption identity. The authenticated user
        can no longer use the identity to send encrypted messages. You cannot
        restore the identity after you delete it. Instead, use the
        CreateCseIdentity method to create another identity with the same
        configuration.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    get:
      operationId: users.settings.cse.identities.gmail.users.settings.cse.identities.get
      description: Retrieves a client-side encryption identity configuration.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}:
    patch:
      operationId: users.settings.cse.identities.gmail.users.settings.cse.identities.patch
      description: Associates a different key pair with an existing client-side
        encryption identity. The updated key pair must validate against Google's
        [S/MIME certificate
        profiles](https://support.google.com/a/answer/7300887).
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/keypairs:
    post:
      operationId: users.settings.cse.keypairs.gmail.users.settings.cse.keypairs.create
      description: Creates and uploads a client-side encryption S/MIME public key
        certificate chain and private key metadata for the authenticated user.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
    get:
      operationId: users.settings.cse.keypairs.gmail.users.settings.cse.keypairs.list
      description: Lists client-side encryption key pairs for an authenticated user.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable:
    post:
      operationId: users.settings.cse.keypairs.gmail.users.settings.cse.keypairs.disable
      description: Turns off a client-side encryption key pair. The authenticated user
        can no longer use the key pair to decrypt incoming CSE message texts or
        sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to
        turn on the key pair. After 30 days, you can permanently delete the key
        pair by using the ObliterateCseKeyPair method.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable:
    post:
      operationId: users.settings.cse.keypairs.gmail.users.settings.cse.keypairs.enable
      description: Turns on a client-side encryption key pair that was turned off. The
        key pair becomes active again for any associated client-side encryption
        identities.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:
    get:
      operationId: users.settings.cse.keypairs.gmail.users.settings.cse.keypairs.get
      description: Retrieves an existing client-side encryption key pair.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate:
    post:
      operationId: users.settings.cse.keypairs.gmail.users.settings.cse.keypairs.obliterate
      description: Deletes a client-side encryption key pair permanently and
        immediately. You can only permanently delete key pairs that have been
        turned off for more than 30 days. To turn off a key pair, use the
        DisableCseKeyPair method. Gmail can't restore or decrypt any messages
        that were encrypted by an obliterated key. Authenticated users and
        Google Workspace administrators lose access to reading the encrypted
        messages.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/filters:
    get:
      operationId: users.settings.filters.gmail.users.settings.filters.list
      description: Lists the message filters of a Gmail user.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    post:
      operationId: users.settings.filters.gmail.users.settings.filters.create
      description: "Creates a filter. Note: you can only create a maximum of 1,000 filters."
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
  /gmail/v1/users/{userId}/settings/filters/{id}:
    get:
      operationId: users.settings.filters.gmail.users.settings.filters.get
      description: Gets a filter.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    delete:
      operationId: users.settings.filters.gmail.users.settings.filters.delete
      description: Immediately and permanently deletes the specified filter.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
  /gmail/v1/users/{userId}/settings/forwardingAddresses:
    get:
      operationId: users.settings.forwardingAddresses.gmail.users.settings.forwardingAddresses.list
      description: Lists the forwarding addresses for the specified account.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    post:
      operationId: users.settings.forwardingAddresses.gmail.users.settings.forwardingAddresses.create
      description: Creates a forwarding address. If ownership verification is
        required, a message will be sent to the recipient and the resource's
        verification status will be set to `pending`; otherwise, the resource
        will be created with verification status set to `accepted`. This method
        is only available to service account clients that have been delegated
        domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}:
    get:
      operationId: users.settings.forwardingAddresses.gmail.users.settings.forwardingAddresses.get
      description: Gets the specified forwarding address.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    delete:
      operationId: users.settings.forwardingAddresses.gmail.users.settings.forwardingAddresses.delete
      description: Deletes the specified forwarding address and revokes any
        verification that may have been required. This method is only available
        to service account clients that have been delegated domain-wide
        authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/delegates:
    get:
      operationId: users.settings.delegates.gmail.users.settings.delegates.list
      description: Lists the delegates for the specified account. This method is only
        available to service account clients that have been delegated
        domain-wide authority.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    post:
      operationId: users.settings.delegates.gmail.users.settings.delegates.create
      description: Adds a delegate with its verification status set directly to
        `accepted`, without sending any verification email. The delegate user
        must be a member of the same Google Workspace organization as the
        delegator user. Gmail imposes limitations on the number of delegates and
        delegators each user in a Google Workspace organization can have. These
        limits depend on your organization, but in general each user can have up
        to 25 delegates and up to 10 delegators. Note that a delegate user must
        be referred to by their primary email address, and not an email alias.
        Also note that when a new delegate is created, there may be up to a one
        minute delay before the new delegate is available for use. This method
        is only available to service account clients that have been delegated
        domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
  /gmail/v1/users/{userId}/settings/delegates/{delegateEmail}:
    get:
      operationId: users.settings.delegates.gmail.users.settings.delegates.get
      description: Gets the specified delegate. Note that a delegate user must be
        referred to by their primary email address, and not an email alias. This
        method is only available to service account clients that have been
        delegated domain-wide authority.
      security:
        - OAuth2:
            - https://mail.google.com/
            - https://www.googleapis.com/auth/gmail.modify
            - https://www.googleapis.com/auth/gmail.readonly
            - https://www.googleapis.com/auth/gmail.settings.basic
    delete:
      operationId: users.settings.delegates.gmail.users.settings.delegates.delete
      description: Removes the specified delegate (which can be of any verification
        status), and revokes any verification that may have been required for
        using it. Note that a delegate user must be referred to by their primary
        email address, and not an email alias. This method is only available to
        service account clients that have been delegated domain-wide authority.
      security:
        - OAuth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://mail.google.com/: Read, compose, send, and permanently delete all your
              email from Gmail
            https://www.googleapis.com/auth/gmail.addons.current.action.compose: Manage drafts and send emails when you interact with the add-on
            https://www.googleapis.com/auth/gmail.addons.current.message.action: View your email messages when you interact with the add-on
            https://www.googleapis.com/auth/gmail.addons.current.message.metadata: View your email message metadata when the add-on is running
            https://www.googleapis.com/auth/gmail.addons.current.message.readonly: View your email messages when the add-on is running
            https://www.googleapis.com/auth/gmail.compose: Manage drafts and send emails
            https://www.googleapis.com/auth/gmail.insert: Add emails into your Gmail mailbox
            https://www.googleapis.com/auth/gmail.labels: See and edit your email labels
            https://www.googleapis.com/auth/gmail.metadata: View your email message metadata
              such as labels and headers, but not the email body
            https://www.googleapis.com/auth/gmail.modify: Read, compose, and send emails from your Gmail account
            https://www.googleapis.com/auth/gmail.readonly: View your email messages and settings
            https://www.googleapis.com/auth/gmail.send: Send email on your behalf
            https://www.googleapis.com/auth/gmail.settings.basic: See, edit, create, or
              change your email settings and filters in Gmail
            https://www.googleapis.com/auth/gmail.settings.sharing: Manage your sensitive
              mail settings, including who can manage your mail
